### ISSUE TITLE
Forms within Thymeleaf templates generate an Exception

### ISSUE THREAD

**Issue by eilonreshef** [thymeleaf/thymeleaf-extras-springsecurity#34]
E.g.,
<form role="form" th:action="login" method="post">
with pages that do not require a login attempt to add a CSRF token, which is "too late" because some of the response has already been committed.

Suggested resolution: when using extras-springsecurity, (conditionally?) force generation of the session before starting to write to the buffer. (This is easily achievable using a Filter outside Thymeleaf but is somewhat tricky to identify)

Caused by: java.lang.IllegalStateException: Cannot create a session after the response has been committed
    at org.apache.catalina.connector.Request.doGetSession(Request.java:2886)
    at org.apache.catalina.connector.Request.getSession(Request.java:2256)
    at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:895)
    at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:907)
    at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:240)
    at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:240)
    at org.springframework.security.web.csrf.HttpSessionCsrfTokenRepository.saveToken(HttpSessionCsrfTokenRepository.java:63)
    at org.springframework.security.web.csrf.LazyCsrfTokenRepository$SaveOnAccessCsrfToken.saveTokenIfNecessary(LazyCsrfTokenRepository.java:176)
    at org.springframework.security.web.csrf.LazyCsrfTokenRepository$SaveOnAccessCsrfToken.getToken(LazyCsrfTokenRepository.java:128)
    at org.springframework.security.web.servlet.support.csrf.CsrfRequestDataValueProcessor.getExtraHiddenFields(CsrfRequestDataValueProcessor.java:71)
    at org.thymeleaf.spring4.requestdata.RequestDataValueProcessor4Delegate.getExtraHiddenFields(RequestDataValueProcessor4Delegate.java:86)
    at org.thymeleaf.spring4.requestdata.RequestDataValueProcessorUtils.getExtraHiddenFields(RequestDataValueProcessorUtils.java:155)
    at org.thymeleaf.spring4.processor.SpringActionTagProcessor.doProcess(SpringActionTagProcessor.java:116)
    at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:98)
    at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)

**Comment by robinvalk** [comment]
I'm currently having the same issue, how did you manage to solve this?

**Comment by eilonreshef** [comment]
Here's the filter code we added (a few items are our own but they can be easily stripped out):

```
private static class SessionCreatorFilter implements Filter {
    private static final String FILTER_NAME = ...;

    public void init(FilterConfig filterConfig) throws ServletException {
        logger.debug("Initializing " + FILTER_NAME);
    }

    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
        HttpServletRequest httpServletRequest = (HttpServletRequest) request;

        String requestURI = httpServletRequest.getRequestURI();

        // Forcibly generate a session so that we can create CSRF when needed - Thymeleaf does that
        // See https://github.com/thymeleaf/thymeleaf-extras-springsecurity/issues/34
        if (!requestURI.startsWith(...))
            httpServletRequest.getSession(true);

        chain.doFilter(request, response);
    }

    public void destroy() {
        logger.debug("Destroying " + FILTER_NAME);
    }
}
```

**Comment by danielfernandez** [comment]
This the same as thymeleaf/thymeleaf-spring#110, which derived into spring-projects/spring-security#3906.

I believe there is enough information and explanation about this scenario in both tickets, so I'm closing this one. Anyway, please reopen it if you feel there is any additional aspect that should be further discussed.

**Comment by eilonreshef** [comment]
Hi Daniel, thanks for the pointer to the related issues. One small suggestion: it may be worthwhile (and easy) to catch this particular exception in Thymeleaf 3.0 and point (in the error message) to the above cases. Presumably this is not a rare issue, and is new to people migrating to 3.0.

Hope this helps, Eilon
