### ISSUE TITLE
Exception while using Spring Security Extras 4 with Spring Webflux

### ISSUE THREAD

**Issue by sanaulla123** [thymeleaf/thymeleaf-extras-springsecurity#53]
I am trying to use `sec:authorize="isAuthenticated()"` but it resulted in the following exception:

The stacktrace:

    Caused by: org.thymeleaf.exceptions.ConfigurationException: Thymeleaf execution context is not a web context (implementation of org.thymeleaf.context.IWebContext). 
    Spring Security integration can only be used in web environments.
	at org.thymeleaf.extras.springsecurity4.dialect.processor.AuthorizeAttrProcessor.isVisible(AuthorizeAttrProcessor.java:76)
	at org.thymeleaf.standard.processor.AbstractStandardConditionalVisibilityTagProcessor.doProcess(AbstractStandardConditionalVisibilityTagProcessor.java:61)
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
	... 392 common frames omitted

The Thymeleaf Template Engine is configured using its reactive classes as shown below:

    @Bean
    public SpringWebFluxTemplateEngine templateEngine() {
		SpringWebFluxTemplateEngine templateEngine = new SpringWebFluxTemplateEngine();
		templateEngine.setTemplateResolver(templateResolver());
		templateEngine.addDialect(new LayoutDialect());
		templateEngine.addDialect(new SpringSecurityDialect());
		return templateEngine;
    }

How do we use this spring security dialect with Spring Webflux?

**Comment by chat491231702** [comment]
I got the same problem too !!

**Comment by danielfernandez** [comment]
Please note the `thymeleaf-extras-springsecurity4` package does not contain support for Spring WebFlux.

A new `thymeleaf-extras-springsecurity5` package is currently being prepared and should be soon published, adding support for Spring Security 5 in Spring WebFlux applications.
