### ISSUE TITLE
The auth infrastructure could not create utility for the specific version of Spring beingused. Currently Spring 3.0, 3.1, 3.2 and 4.x are supported.

### ISSUE THREAD

**Issue by heatherm** [thymeleaf/thymeleaf-extras-springsecurity#56]
I'm seeing an error when rendering a template that points to the class loader not finding spring or various org.springframework classes present at the application's class path. 

If I remove the sec:authorize attribute from the template, the page renders.

Template:
```
            <li class="nav-item" sec:authorize="hasRole('ROLE_ADMIN')">
                <a class="nav-link" th:href="@{/admin/}">Admin</a>
            </li>
```

I'm using Spring 5.0.6.RELEASE, spring-security-core 5.0.5.RELEASE, with the following thymeleaf versions:
```
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf-spring5</artifactId>
            <version>3.0.9.RELEASE</version> 
        </dependency>

        <dependency>
            <groupId>nz.net.ultraq.thymeleaf</groupId>
            <artifactId>thymeleaf-layout-dialect</artifactId>
            <version>2.3.0</version>
        </dependency>

        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity4</artifactId>
            <version>3.0.2.RELEASE</version>
        </dependency>
```

Error:
```
Caused by: java.lang.ExceptionInInitializerError: null
	at org.thymeleaf.extras.springsecurity4.auth.SpringVersionSpecificUtils.<clinit>(SpringVersionSpecificUtils.java:107) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.extras.springsecurity4.auth.AuthUtils.authorizeUsingAccessExpression(AuthUtils.java:209) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.extras.springsecurity4.dialect.processor.AuthorizeAttrProcessor.isVisible(AuthorizeAttrProcessor.java:91) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.standard.processor.AbstractStandardConditionalVisibilityTagProcessor.doProcess(AbstractStandardConditionalVisibilityTagProcessor.java:61) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.spring5.view.ThymeleafView.renderFragment(ThymeleafView.java:355) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.thymeleaf.spring5.view.ThymeleafView.render(ThymeleafView.java:188) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1325) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1069) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1008) ~[twitch-integration-admin-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	... 82 common frames omitted
Caused by: org.thymeleaf.exceptions.ConfigurationException: The auth infrastructure could not create utility for the specific version of Spring beingused. Currently Spring 3.0, 3.1, 3.2 and 4.x are supported.
```

According to this: https://github.com/thymeleaf/thymeleaf-extras-springsecurity/issues/47 I should be able to thymeleaf-extras-springsecurity4 with my current versions. Any idea where this is falling down? Thanks in advance!

**Comment by graham-collinson** [comment]
Do you have spring boot? thymeleaf-extras-springsecurity4 is currently ok for me with spring boot 2.0.4

**Comment by heatherm** [comment]
Yep, using spring boot 2.0.2.RELEASE on this end.

This was helpful in my case: https://stackoverflow.com/questions/27202939/could-not-build-classfile-archiveexception, with an upgrade to the latest javassist fixing the issue.
